export const routes = {
    login: '/',
    dahsboard: '/dashboard',
    users: '/users',
    user_roles: '/user-roles',
    expenseTypes: '/expense-types',
    expenses: '/expenses',
    branches: '/branches',
    brands: '/brands',
    units: '/units',
    vendors: '/vendors',
    customers: '/customers',
    categories: '/categories',
    items: '/items',
    tables: '/tables',
    orders: '/orders',
    reports: '/reports',
    salesReport: '/reports/sales',
    expenseReports: '/reports/expenses',
    kitchen: '/kitchen',
    settings: '/settings'
}